blog/app/views/main.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from app.forms import PostsForm
from app.models import Posts
from flask_login import current_user
from app.extensions import db


main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():
    form = PostsForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            # 获取当前登录用户对象
            user = current_user._get_current_object()
            # 创建对象
            p = Posts(content=form.content.data, user=user)
            # 保存到数据库
            db.session.add(p)
            flash('发表成功')
            return redirect(url_for('main.index'))
        else:
            flash('请登录后再发表')
            return redirect(url_for('user.login'))
    # 查询博客
    # posts = Posts.query.filter(Posts.rid == 0).order_by(Posts.timestamp.desc())
    # 分页查询
    page = request.args.get('page', 1, int)
    pagination = Posts.query.filter(Posts.rid == 0).order_by(Posts.timestamp.desc()).paginate(page, per_page=3, error_out=False)
    posts = pagination.items
    return render_template('main/index.html', form=form, posts=posts, pagination=pagination)


@main.route('/ajax/')
def ajax():
    return render_template('main/ajax.html')


# 处理ajax请求
@main.route('/check/', methods=['GET', 'POST'])
def check():
    import json
    name = request.values.get('name')
    return json.dumps({'name': name})

blog/app/views/posts.py
from flask import Blueprint, jsonify
from flask_login import current_user


posts = Blueprint('posts', __name__)


@posts.route('/collect/<int:pid>')
def collect(pid):
    # 判断是否已经收藏
    if current_user.is_favorite(pid):
        # 取消收藏
        current_user.del_favorite(pid)
        return jsonify({'status': '收藏'})
    else:
        # 添加收藏
        current_user.add_favorite(pid)
        return jsonify({'status': '取消收藏'})

blog/app/templates/main/ajax.html
{% extends 'common/base.html' %}

{% block title %}ajax请求测试{% endblock %}

{% block page_content %}
    <button id="get">GET请求</button>
    <button id="post">POST请求</button>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        function callback(data) {
            alert(data.name)
        }
        $(function () {
            $('#get').click(function () {
                $.get('/check/', 'name=xiaoming', callback, 'json')
            })
            $('#post').click(function () {
                $.post('/check/', 'name=ergouzi', callback, 'json')
            })
        })
    </script>
{% endblock %}

blog/app/templates/main/index.html
{% extends 'common/base.html' %}

{# 导入分页显示的宏 #}
{% from 'common/macro.html' import show_pagination %}

{% block title %}首页{% endblock %}

{% block page_content %}
    {{ quick_form(form) }}
    {% for p in posts %}
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static', filename='upload/'+p.user.icon) }}" alt="头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right;">{{ moment(p.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ p.user.username }}</h4>
                {{ p.content }}
            {% if current_user.is_authenticated %}
                <div class="collect" url="{{ url_for('posts.collect', pid=p.id) }}">收藏</div>
            {% endif %}
            </div>
        </div>
    {% endfor %}
    {# 显示分页导航条， 可以传递额外的参数 #}
    {{ show_pagination(pagination, 'main.index', id=3, name='xxx') }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        $(function () {
            $('.collect').click(function () {
                // 回调函数中的this没有意义，因此需要先记录下来
                _this = this
                $.get($(this).attr('url'), function (data) {
                    $(_this).text(data.status)
                })
            })
        })
    </script>
{% endblock %}