blog/app/views/user.py
from flask import Blueprint, flash, redirect, url_for, render_template, request, current_app
from app.forms import RegisterForm, LoginForm, UploadForm
from app.email import send_mail
from app.models import User
from app.extensions import db, photos
from flask_login import login_user, logout_user, login_required, current_user
from PIL import Image
import os


user = Blueprint('user', __name__)


# 用户注册
@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 创建用户对象
        u = User(username=form.username.data,
                 password=form.password.data,
                 email=form.email.data)
        # 保存到数据库
        db.session.add(u)
        # 手动提交，因为生成token时需要使用用户id
        db.session.commit()
        # 生成包含有效信息的token
        token = u.generate_activate_token()
        # 发送激活邮件
        send_mail('账户激活', form.email.data, 'email/activate.html', token=token)
        flash('注册成功，请点击邮件中的链接以完成激活')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


# 用户激活
@user.route('/activate/<token>')
def activate(token):
    if User.check_activate_token(token):
        return redirect(url_for('user.login'))
    else:
        return redirect(url_for('main.index'))


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # 根据用户名查找数据库
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('无效的用户名')
        elif not u.confirmed:
            flash('请先激活，然后再登录')
        elif u.verify_password(form.password.data):
            # 用户登录
            login_user(u, remember=form.remember.data)
            flash('登录成功')
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('无效的密码')
    return render_template('user/login.html', form=form)


# 退出登录
@user.route('/logout/')
def logout():
    logout_user()
    flash('您已退出登录')
    return redirect(url_for('main.index'))


# 用户详情
@user.route('/profile/')
# 保护路由，需要登录才能访问
@login_required
def profile():
    return render_template('user/profile.html')


# 修改头像
@user.route('/icon/', methods=['GET', 'POST'])
def icon():
    form = UploadForm()
    if form.validate_on_submit():
        # 提取后缀
        suffix = os.path.splitext(form.icon.data.filename)[1]
        # 生成随机文件名
        filename = random_string() + suffix
        # 保存上传文件
        photos.save(form.icon.data, name=filename)
        # 拼接完整文件路径名
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        # 生成缩略图
        img = Image.open(pathname)
        # 设置尺寸
        img.thumbnail((64, 64))
        # 覆盖保存图片
        img.save(pathname)
        # 删除原来的头像（默认头像除外）
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon))
        # 保存到数据库
        current_user.icon = filename
        db.session.add(current_user)
    # 获取url
    img_url = url_for('static', filename='upload/'+current_user.icon)
    return render_template('user/icon.html', form=form, img_url=img_url)


# 生成随机字符串
def random_string(length=32):
    import random
    base_str = 'abcdefghijklmnopqrstuvwxyz1234567890'
    return ''.join(random.choice(base_str) for i in range(length))

blog/app/templates/common/base.html
{# 继承自bootstrap的基础模板 #}
{% extends 'bootstrap/base.html' %}

{# 导入快速渲染表单的宏 #}
{% from 'bootstrap/wtf.html' import quick_form %}

{# 定制导航条 #}
{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">版块一</a></li>
                    <li><a href="#">版块二</a></li>
                    <li><a href="#">版块三</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.profile') }}">用户详情</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">修改邮箱</a></li>
                            <li><a href="{{ url_for('user.icon') }}">修改头像</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('user.login') }}">登录</a></li>
                    <li><a href="{{ url_for('user.register') }}">注册</a></li>
                {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% endblock %}

{# 定制内容 #}
{% block content %}
    <div class="container">
        {# 消息闪烁 #}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        {# 页面内容 #}
        {% block page_content %}默认内容{% endblock %}
    </div>
{% endblock %}

{# 加载收藏夹图标 #}
{% block head %}
    {{ super() }}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
{% endblock %}

{# 加载moment相关js #}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

blog/app/templates/common/macro.html
{# 定义分页显示的宏 #}
{% macro show_pagination(pagination, endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 上一页 #}
            <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {# 中间页码 #}
            {% for p in pagination.iter_pages() %}
                {% if p %}
                <li {% if p == pagination.page %}class="active"{% endif %}><a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a></li>
                {% else %}
                <li><a href="#">&hellip;</a></li>
                {% endif %}
            {% endfor %}

            {# 下一页 #}
            <li {% if not pagination.has_next %}class="disabled"{% endif %}>
                <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}